### ISSUE TITLE
Title mismatch in English and French for event titles in the console for The Playhouse.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#12]
Hi @kmdvs , When you get a chance can you look at this English/French title mismatch for the The Playhouse.

![Image](https://github.com/user-attachments/assets/a53086d4-deed-409d-8f8a-b739b4730693)

Here is the [link](https://console.footlight.io/events/footlight:theplayhouse-ca_josephine-burlesque-cabaret-dream-play).

**Comment by tammy-culture** [comment]
@kmdvs There are other examples of English/French title mismatches for events.

![Image](https://github.com/user-attachments/assets/6cdd7f55-1edc-47d3-819f-eb7d895a860b)

[Link](https://console.footlight.io/events/footlight:theplayhouse-ca_new-north-collective-circumpolar-soundscape)

**Comment by tammy-culture** [comment]
@kmdvs There are about 18 events that have mismatched English/French titles.

[Link](https://console.footlight.io/sources/1)

**Comment by kmdvs** [comment]
Yes, these are all the "doublons"... So we can refer to [Issue 7](https://github.com/culturecreates/footlight-console/issues/7)

**Comment by tammy-culture** [comment]
Note: This needs pre-processing and we are not building a custom scraper for the Playhouse when they will be adding JSON-LD on their site.
