### ISSUE TITLE
Console picking up unnecessary information in the title

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#18]
It looks like the console is picking up unnecessary information in the title:
https://console.footlight.io/sources/1

Please take a look when you can.

**Comment by tammy-culture** [comment]
The title should be just Faon

![Image](https://github.com/user-attachments/assets/5e24e42b-0566-4a29-b751-8a1804de28c5)



And not:

Faon - Les 2 Mondes (Théâtre)

**Comment by kmdvs** [comment]
OK done :)
