### ISSUE TITLE
imperialtheatre-ca wrong performers

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-console#3]
imperialtheatre-ca  should not include itself as a performer. 
https://kg.artsdata.ca/entity?uri=http%3A%2F%2Fkg.footlight.io%2Fresource%2Fimperialtheatre-ca_symphony-new-brunswick-classis-film-with-live-music-the-china-syndrome

**Comment by kmdvs** [comment]
[Duplicate](https://github.com/culturecreates/footlight-console/issues/5)
