### ISSUE TITLE
Remove Imperial Theatre from Performed By in the Footlight Console

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#5]
Please remove Imperial Theatre in Performed By

![Image](https://github.com/user-attachments/assets/ffed9de4-779c-4dc7-9436-e672420468c9)

The Console is adding Imperial Theatre as a Performer to the majority events.

https://console.footlight.io/sources/12

**Comment by kmdvs** [comment]
OK, it is done. They changed the title slightly, so the string was not removed anymore. 
Note: this is an old site, not updated to the standard.

**Comment by tammy-culture** [comment]
Thanks.  I got confirmation from client that we are not going to update it. Cheers.
