### ISSUE TITLE
Can we fix the red flags on this site? https://console.footlight.io/events?filter=updated&seedurl=theplayhouse-ca

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#7]
@kmdvs Can you take a look at the red flag issues on this site please: https://console.footlight.io/events?filter=updated&seedurl=theplayhouse-ca

**Comment by kmdvs** [comment]
@tammy-culture Just to make sure :) You want me to _assess_ the work needed, or to _correct_ the issues?

**Comment by tammy-culture** [comment]
@kmdvs Please fix this issue.  Thank you.  It is a client site.  Or let me know what is going on with the doubles?

**Comment by kmdvs** [comment]
@tammy-culture OK, and for ongoing maintenance, should I add that site back to flags > 12 means correcting issues (previously, from July 18 communications, Playhouse should not be touched).

**Comment by kmdvs** [comment]
@tammy-culture @saumier To really correct the doubles, we need the DSL code to synchronize en and fr calendar pages... 

Ref Gregory in Slack: "Here is what I propose. This is a special case that we need to solve for all bilingual sites. So I will add a new DSL called “url_array_xpath=“.  This will load each url in the array and apply the given xpath. In our case the complete source algorithm would be “xpath=//a[@class=‘main-link’]/@href;url_array_xpath=//a[contains(@class,“language-link”)]/@href;ruby=$array.map{ |url| “https://placedesarts.com” + url } (edited) "

**Comment by kmdvs** [comment]
@tammy-culture @saumier The calendar URL structure is sufficiently similar that by sorting, the doubles issue was reduced from 100% error to ~24% error... If there's no time for new DSL code, there are 3 possibilites: 
1. Disable the errors: this is manually done, needs human verification after each update (currently 7 days)
2. Preprocessing as in Gatineau: I found a "node id" in the pages, which is identical for fr and en pages of the same event. I could use that id to preprocess URLs into a sorted list by id, and the site would use that as input. Caveat: as with Gatineau and Culture Mauricie, we'd have to verify that "caching issue" that may provoke a desynchronization... 
3. Manually arrange the list of URLs / URIs and load that list. Redo every week / 2 weeks
[Playhouse url-uri.xlsx](https://github.com/user-attachments/files/16896912/Playhouse.url-uri.xlsx)
 
 So how should I address that?

**Comment by kmdvs** [comment]
@tammy-culture The pricing is unusual for some events, like [this one](https://theplayhouse.ca/en/schedule-and-tickets/momentum-isolation). I'll put 
AggregateOffer note: "Plus taxes"
AggregateOffer type: Paid
Price: 0.0
Price description: "PAY WHAT YOU WILL - TICKETS REQUIRED"

So even though Price is 0, this is different from Free

**Comment by kmdvs** [comment]
@tammy-culture OK, apart from the issue with some doubles, the site is good now :)

**Comment by kmdvs** [comment]
@tammy-culture Do you want to do something for the doubles?

**Comment by tammy-culture** [comment]
@Kim we are going to leave the double as is for now.
