### ISSUE TITLE
Can we automate the linking of the following "Organized By" property for The Playhouse.

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-console#8]
I have added a new organization resource to Footlight Console and the console is not automatically picking it up.

Please see below:

![Image](https://github.com/user-attachments/assets/ddfdde19-8b6a-46de-ac0c-9f5e3c1f181f)

https://console.footlight.io/sources/6

Can we fix this?

Thank you.

**Comment by kmdvs** [comment]
OK, it's done :)
